package ui;

/**
 *
 * @author Vega
 */
public class InterfazGráfica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGráfica
     */
    public InterfazGráfica() {
        super("Compiladores - PL1");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        lbLongitud = new javax.swing.JLabel();
        lbElegir = new javax.swing.JLabel();
        tgBtnER1 = new javax.swing.JToggleButton();
        tgBtnER2 = new javax.swing.JToggleButton();
        tfNumero = new javax.swing.JTextField();
        tfLongitud = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setFocusable(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        titulo.setText("¿Qué expresión regular quieres modificar?");

        lbNumero.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbNumero.setText("Nº de cadenas a generar: ");

        lbLongitud.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbLongitud.setText("Longitud de las cadenas a generar: ");

        lbElegir.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbElegir.setText("Elige la Expresión Regular que quieras usar para generar las cadenas: ");

        tgBtnER1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tgBtnER1.setText("Que haya al menos 3 as seguidas en la cadena");
        tgBtnER1.setFocusable(false);

        tgBtnER2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tgBtnER2.setText("Que la cadena esté compuesta por secuencias 'abc' o 'cba'");
        tgBtnER2.setFocusable(false);

        tfNumero.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tfNumero.setText("jTextField1");

        tfLongitud.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        tfLongitud.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbElegir)
                            .addComponent(lbLongitud)
                            .addComponent(lbNumero)
                            .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgBtnER2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgBtnER1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(titulo)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(lbNumero)
                .addGap(12, 12, 12)
                .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbLongitud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lbElegir)
                .addGap(18, 18, 18)
                .addComponent(tgBtnER1)
                .addGap(18, 18, 18)
                .addComponent(tgBtnER2)
                .addGap(36, 36, 36)
                .addComponent(btnVolver)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGráfica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lbElegir;
    private javax.swing.JLabel lbLongitud;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JTextField tfLongitud;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JToggleButton tgBtnER1;
    private javax.swing.JToggleButton tgBtnER2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
